### ISSUE TITLE
Dependency Vulnerability

### ISSUE THREAD

**Issue by shirtleton** [liamqma/beanstalkify#8]
`Lodash` - [Prototype Pollution]( https://www.npmjs.com/advisories/1065)

![image](https://user-images.githubusercontent.com/34657853/61751427-84091280-ad65-11e9-86c9-1cf6462ca65a.png)

**Comment by liamqma** [comment]
Thanks @shirtleton ,

I will do a `npm audit` and try removing Vulnerabilities.

**Comment by liamqma** [comment]
Hi @shirtleton ,

I've created this PR https://github.com/liamqma/beanstalkify/pull/10. I will do some more testing then merge it.

**Comment by liamqma** [comment]
Lodash has been upgraded to v4.17.15.
